### ISSUE TITLE
Frontend usage metrics

### ISSUE THREAD

**Issue by jmfernandez** [inab/openEbench-frontend#2]
In order to identify the hotspots (and the least used pages) of the frontend, it should have integrated some usage measurement, like Google Analytics. For Angular 2+ there is a tutorial explaining it:

https://scotch.io/tutorials/integrating-google-analytics-with-angular-2

which could be useful

**Comment by vsundesha** [comment]
Done in 4c64a5725987ed81a55c730527996ff70b890be5
