### ISSUE TITLE
Broken tool search in technical monitoring

### ISSUE THREAD

**Issue by AsierGonzalez** [inab/openEbench-frontend#39]
I have struggled to find the [CARD database](https://openebench.bsc.es/tool/card) using the search box in [the OpenEBench Technical Monitoring site](https://openebench.bsc.es/tool?search=). The following is what I tried without any luck:
- Search for both ["card"](https://openebench.bsc.es/tool?search=card) and ["CARD"](https://openebench.bsc.es/tool?search=CARD).
- Change the number of items per page from 10 (default) to 20.
- Change the search space ("Search in") from "Name" to "Name & Description".

I finally got what I expected when I searched for ["comprehensive"](https://openebench.bsc.es/tool?search=comprehensive), which is part of the full name.

Together with @jmfernandez and @redmitry, we have found that the search is based on querying the same dev REST API endpoint both in the prod and dev websites: `https://dev-openebench.bsc.es/monitor/rest/edam/aggregate`.

However, this bug doesn't explain why the tool isn't found in the results. The query returns 51 results in [dev](https://dev-openebench.bsc.es/monitor/rest/edam/aggregate?projection=description&projection=web&name=card&label=null) and 50 in [prod](https://openebench.bsc.es/monitor/rest/edam/aggregate?projection=description&projection=web&name=card&label=null) and in both cases CARD is one of the tools found.

 ![image](https://user-images.githubusercontent.com/11410715/155963721-d203b6e8-310d-4728-ba95-5757a66f80ab.png)

The real problem is threefold:
 - The results are not ranked in any way.
 - The web app requests a limited number of results based on the "items per page" drop-down list: this sets the `Range` header in the request to something like `Range: items=0-10`.
 - There is **no pagination!!**: The number of "items per page" is, in reality, the max number of results and there is no way to navigate through the rest if there are more.

In addition, one thing that makes the search results hard to interpret is that although the search can be applied to the name, description or both, the UI only shows the label and the description; the name is not shown anywhere. I think it would be helpful to have an option to search in the label too, which seems to be more succinct or show the name instead.

**Comment by dominikbruechner** [comment]
finally merged with https://github.com/inab/openEbench-frontend/pull/42
